from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from django.conf.urls.static import static
from .views import (AccountPostsListView, PostCreateView, CategoryPostsListView,
                    PostSingleGetView,
                    SearchApiView, PostSearchView, PostFrontGetView, PostSecondryGetView, PostMainBottomGetView,
                    PostAccountSearchView,
                    ArticleUpdateView, ArticleDeleteView, ArticleEditDetail,
                    LinkTool,
                    DraftPostsCreateView,
                    DraftPostssAccView, DraftPostsDeleteView, DraftPostsEditDetail, DraftPostsSingleGetView, DraftPostsUpdateView, DraftPostsPublishView, AuthorOtherPostsListView)

# like_viewset = DefaultRouter()
# like_viewset.register('', PostLikeViewset),

# bookmark_viewset = DefaultRouter()
# bookmark_viewset.register('', PostBookMarkViewset),
# comment_like_viewset = DefaultRouter()
# comment_like_viewset.register('', CommentLikeViewset),

urlpatterns = [
    path('linktool/', LinkTool.as_view()),
    path('save-edited-draft/', DraftPostsPublishView.as_view(),
         name="save-edited-draft"),
    path('edit-draft/', DraftPostsUpdateView.as_view(), name="edit-draft"),
    path('draft-detail/', DraftPostsSingleGetView.as_view(), name="draft-detail"),
    path('draft-edit-detail/', DraftPostsEditDetail.as_view(),
         name="draft-edit-detail"),
    path('delete-draft/', DraftPostsDeleteView.as_view(), name="delete-draft"),
    path('drafts-acc/', DraftPostssAccView.as_view(), name="drafts-acc"),
    path('draft-create/', DraftPostsCreateView.as_view(), name="draft-create"),
    path('article-front/', PostFrontGetView.as_view(), name="article-front"),
    path('article-secondry/', PostSecondryGetView.as_view(),
         name="article-secondry"),
    path('post-main-bottom/', PostMainBottomGetView.as_view(),
         name="article-main-bottom"),
    path('search-articles/', PostSearchView.as_view(), name="search-articles"),
    path('search-account-articles/', PostAccountSearchView.as_view(),
         name="search-account-articles"),
    path('search-main/', SearchApiView.as_view(), name="search-main"),
    path('articles-detail/', PostSingleGetView.as_view(), name="articles-detail"),
    path('category-articles/', CategoryPostsListView.as_view(),
         name="category-articles-list"),
    path('account-articles/', AccountPostsListView.as_view(),
         name="account-articles-list"),
    path('articles-create/', PostCreateView.as_view(), name="articles-create"),
    path('edit-article/', ArticleUpdateView.as_view(), name="edit-articles"),
    path('delete-article/', ArticleDeleteView.as_view(), name="delete-articles"),
    path('article-edit-detail/', ArticleEditDetail.as_view(),
         name="article-edit-detail"),
    path('author-others/', AuthorOtherPostsListView.as_view(),
         name="account-articles-others"),


    # path('delete-article/<pk>/', ArticleDeleteView.as_view(),name="delete-articles"),


    # path('trending-comments-posts/', PostsCommentsTrending.as_view()),
    # path('trending-writers/', WritersTrending.as_view()),
    # path('trending-comments/', CommentsTrending.as_view()),
    # path('trending-likes/', LikesTrending.as_view()),
    # path('trending-viewed/', ViewsTrending.as_view()),
    # path('response-detail/', ResponseDetailView.as_view()),
    # path('next-article-views/', NextArticleViews.as_view()),
    # path('prev-article-views/', PrevArticleViews.as_view()),
    # path('total-article-views/', TotalArticleViews.as_view()),
    # path('next-article-likes/', NextArticleLikes.as_view()),
    # path('prev-article-likes/', PrevArticleLikes.as_view()),
    # path('total-article-likes/', TotalArticleLikes.as_view()),
    # path('next-article-comments/', NextArticleComments.as_view()),
    # path('prev-article-comments/', PrevArticleComments.as_view()),
    # path('total-article-comments/', TotalArticleComments.as_view()),
    # path('next-account-comments/', NextAccountComments.as_view()),
    # path('prev-account-comments/', PrevAccountComments.as_view()),
    # path('total-account-comments/', TotalAccountComments.as_view()),
    # path('next-account-likes/', NextAccountLikes.as_view()),
    # path('prev-account-likes/', PrevAccountLikes.as_view()),
    # path('total-account-likes/', TotalAccountLikes.as_view()),
    # path('next-account-views/', NextAccountViews.as_view()),
    # path('prev-account-views/', PrevAccountViews.as_view()),
    # path('total-account-views/', TotalAccountViews.as_view()),
    # path('total-account-views-likes/', TotalAccountViewsLikes.as_view()),
    # path('total-article-views-likes-comments/', TotalArticleViewsLikesComments.as_view()),
    #####################################################################
    # path('staff-liked-articles/', AdminFollowArticlesListView.as_view()),
    # path('staff-history-articles/', AdminHistoryArticlesListView.as_view()),
    # path('staff-saved-articles/', AdminSavedArticlesListView.as_view()),
    # path('staff-user-responses/', UserComments.as_view()),
    # path('staff-user-articles/', AdminAccountPostsListView.as_view()),
    # path('delete-contact-us/', DeleteContactUsView.as_view()),
    # path('contact-us-single/', ContactUsSingleView.as_view()),
    # path('contact-us-list/', ContactUsListView.as_view()),
    # path('suspended-articles/', SuspendedArticles.as_view()),
    # path('staff-sotiotalk-articles/', SotioTalkArticlesView.as_view()),
    # path('staff-single-article/', StaffPostSingleGetView.as_view()),
    # path('active-or-suspend-articles/', ActiveOrSuspendArticle.as_view()),
    # path('reported-articles/', ReportedArticles.as_view()),
    # path('delete-reported-article/', DeleteReportedArticleView.as_view()),
    # path('delete-reported-all-dis-article/', DeleteAllDistinctReportedArticleView.as_view()),
    # path('delete-reported-comment-request/', DeleteReportedCommentRequestView.as_view()),
    # path('delete-all-dis-reported-comment-request/', DeleteAllDisReportedCommentRequestView.as_view()),
    # path('delete-reported-comment/', DeleteReportedCommentsView.as_view()),
    # path('reported-comments/', ReportedComments.as_view(), name="reported-comments-list"),
    # path('articles/', PostListView.as_view(), name="articles-list"),
    # path('articles-like/', PostSingleLikeInfoView.as_view(), name="articles-like"),
    # path('discover-articles/', DiscoverPostsGetView.as_view(), name="discover-articles-list"),
    # path('like-post/', include(like_viewset.urls)),
    # path('report-post/', ArticleReportCreateView.as_view()),
    # path('report-comment/', CommentReportCreateView.as_view()),
    # path('save-post/', include(bookmark_viewset.urls)),
    # path('save-posts-list/', BookMarkListView.as_view(),name="bookmark-list"),
    # path('history-posts-list/', RecentlyViewedView.as_view(),name="history-list"),
    # path('liked-posts-list/', LikedPostView.as_view(),name="liked-posts-list"),
    # path('muted-articles/', ArticleMuteList.as_view(),name="muted-articles-list"),
    # path('dis-muted-articles/', ArticleMuteDistinctList.as_view(),name="dis-muted-articles-list"),
    # path('mute-article/', ArticleMuteCreateView.as_view(),name="muted-articles-list"),
    # path('delete-mute-article/', ArticleMuteDeleteView.as_view(),name="delete-muted-articles-list"),
    # path('comments-list/', CommentListView.as_view(),name="comments-list"),
    # path('comments-list-spec/', CommentDistinctView.as_view(),name="comments-list-spec"),
    # path('comments-list-spec/', CommentDistinctListView.as_view(),name="comments-list-spec"),
    # path('comment-update/', CommentUpdateView.as_view(),name="comment-update"),
    # path('comment-create/', CommentCreateView.as_view(),name="comment-create"),
    # path('comment-delete/', CommentDeleteView.as_view(),name="comment-delete"),
    # path('posts-stats/', ArticlesStateView.as_view(),name="posts-stats"),
    # path('posts-acc/', ArticlesAccView.as_view(),name="posts-acc"),
    # path('responses-stats/', CommentStateView.as_view(),name="responses-stats"),
    # path('responses-acc/', CommentAccView.as_view(),name="responses-acc"),
    # path('comment-like/', include(comment_like_viewset.urls)),
    # path('notifications-distinct/', NotificationsDistinctListView.as_view(),name="notifications-distinct"),
    # path('doseen-notifications/', DoSeenNotifications.as_view(),name="doseen-notifications"),
    # path('contact-us/', ContactUsCreateView.as_view(),name="contact-us"),
    # path('dashboard/', DashboardView.as_view(),name="dashboard"),
    # path('admin-sidebar-count/', AdminSidebarCountView.as_view(),name="sidebar"),
]
