# Generated by Django 4.2 on 2023-06-18 09:47

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import editorjs_field.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('meta', models.CharField(blank=True, max_length=200, null=True)),
                ('description', editorjs_field.fields.EditorJSField()),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='Politics', max_length=20), blank=True, null=True, size=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
