# Generated by Django 4.2 on 2023-07-06 07:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_draftposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftposts',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='Politics', max_length=200), blank=True, null=True, size=None),
        ),
    ]
