# Generated by Django 4.2 on 2023-07-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_posts_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posts',
            name='is_secondary',
            field=models.BooleanField(default=False),
        ),
    ]
