# Generated by Django 4.2 on 2023-07-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_posts_is_primary_posts_is_secondary'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='read_min',
            field=models.IntegerField(default=2),
        ),
    ]
