# Generated by Django 4.2 on 2023-12-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_issecondary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendingposts',
            name='date',
        ),
        migrations.RemoveField(
            model_name='trendingposts',
            name='update',
        ),
        migrations.RemoveField(
            model_name='trendingposts',
            name='user',
        ),
    ]
