# Generated by Django 4.2 on 2023-12-28 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_delete_readminutesofposts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadMinutesOfPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_min', models.IntegerField(default=2)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.posts')),
            ],
        ),
    ]
