# Generated by Django 4.2 on 2023-12-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_readminutesofposts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaidView',
        ),
    ]
