# Generated by Django 4.2 on 2023-12-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_categoryposts_date_categoryposts_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryposts',
            name='date',
        ),
        migrations.RemoveField(
            model_name='categoryposts',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='isprimary',
            name='date',
        ),
        migrations.RemoveField(
            model_name='isprimary',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='issecondary',
            name='date',
        ),
        migrations.RemoveField(
            model_name='issecondary',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='suspendedpost',
            name='date',
        ),
        migrations.RemoveField(
            model_name='suspendedpost',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='trendingposts',
            name='date',
        ),
        migrations.RemoveField(
            model_name='trendingposts',
            name='updated',
        ),
    ]
