# Generated by Django 4.2 on 2024-01-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_remove_categoryposts_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='read_min',
        ),
    ]
