# Generated by Django 4.2 on 2024-01-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_remove_posts_read_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftposts',
            name='read_min',
            field=models.IntegerField(default=2),
        ),
    ]
